Repository MostBridge/Bridge, pull requests merged in 2023-10, with the labels that each got.

#8 добавил шаблоны приложений api и users. Поключил djoser и simplejwt. Добавил swagger.
  .gitignore
  backend/api/__init__.py
  backend/api/apps.py
  backend/api/urls.py
  backend/api/views.py
  backend/candidate/__init__.py
  backend/candidate/admin.py
  backend/candidate/apps.py
  backend/candidate/migrations/__init__.py
  backend/candidate/models.py
  backend/core/settings.py
  backend/core/urls.py
  backend/users/__init__.py
  backend/users/admin.py
  backend/users/apps.py
  backend/users/migrations/__init__.py
  backend/users/models.py
  backend/users/serializers.py
  poetry.lock
  pyproject.toml
Labels: enhancement, good first issue

#10 added model user
  Makefile
  README.md
  backend/candidate/migrations/0001_users_model.py
  backend/core/settings.py
  backend/users/admin.py
  backend/users/migrations/0001_users_model.py
  backend/users/models.py
Labels: enhancement

#14 added models
  backend/candidate/admin.py
  backend/candidate/migrations/0001_profession_tech_town_models.py
  backend/candidate/models.py
  backend/users/migrations/0001_profession_tech_town_models.py
Labels: enhancement

#18 add enhacements
  backend/api/urls.py
  backend/api/v1/serializers.py
  backend/api/v1/urls.py
  backend/api/v1/views.py
  backend/api/views.py
  backend/candidate/admin.py
  backend/candidate/migrations/0001_initial.py
  backend/candidate/migrations/0001_profession_tech_town_models.py
  backend/candidate/models.py
  backend/core/settings.py
  backend/fixtures/cities.json
  backend/ruff.toml
  backend/users/migrations/0001_initial.py
Labels: enhancement

#17 Feature/api
  backend/api/v1/mixins.py
  backend/api/v1/serializers.py
  backend/api/v1/urls.py
  backend/ruff.toml
Labels: enhancement

#19 fix user and candidate serializers, add email config, add new fixtures
  .env.example
  backend/api/v1/serializers.py
  backend/api/v1/urls.py
  backend/core/settings.py
  backend/fixtures/candidate.json
  backend/fixtures/profession.json
  backend/users/models.py
  backend/users/serializers.py
Labels: enhancement

#26 add email handler
  backend/api/urls.py
  backend/api/v1/urls.py
  backend/api/v1/views.py
  backend/core/settings.py
  backend/core/urls.py
Labels: enhancement

#25 Feature/readme
  README.md
Labels: documentation

#24 add factories
  Makefile
  backend/candidate/factories.py
  backend/candidate/management/commands/create_contacts.py
  backend/candidate/management/commands/create_profession.py
  backend/candidate/migrations/0002_region_distinct_optional.py
  backend/candidate/models.py
  backend/candidate/utils/db_command.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#30 new factories
  Makefile
  backend/candidate/factories.py
  backend/candidate/management/commands/create_favorites.py
  backend/tests/test_models.py
  backend/tests/test_views.py
  poetry.lock
  pyproject.toml
  pytest.ini
Labels: enhancement

#32 add additional fileds to candidate model
  backend/api/v1/serializers.py
  backend/api/v1/urls.py
  backend/api/v1/views.py
  backend/candidate/admin.py
  backend/candidate/migrations/0001_initial.py
  backend/candidate/migrations/0004_candidate_experience_candidate_first_name_and_more.py
  backend/candidate/models.py
  backend/candidate/validators.py
  backend/core/settings.py
  backend/tests/fixtures.py
  backend/tests/test_views.py
Labels: enhancement

#37 added pagination and part of filters
  backend/api/v1/filters.py
  backend/api/v1/paginations.py
  backend/api/v1/views.py
  backend/candidate/factories.py
  backend/candidate/migrations/0005_profession_slug_alter_candidate_photo_and_more.py
  backend/candidate/models.py
  backend/core/settings.py
  poetry.lock
  pyproject.toml
  test.http
Labels: enhancement

#45 fix serializers and factories
  .github/workflows/Deploy.yml
  backend/api/v1/serializers.py
  backend/candidate/factories.py
Labels: bug, enhancement

#47 added tech, emp, filters and pagination
  backend/api/v1/filters.py
  backend/candidate/factories.py
  backend/core/settings.py
  backend/fixtures/data.json
  backend/fixtures/tech_emp.json
  backend/tests/test_models.py
  poetry.lock
  test.http
Labels: enhancement
